<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\State;
use App\Models\City;
use App\Models\Municipality;
use App\Models\Parish;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Desactivar llaves foráneas para el truncado masivo
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Limpiar tablas en el orden inverso de dependencia
        Parish::truncate();
        Municipality::truncate();
        City::truncate();
        State::truncate();

        // Reactivar llaves foráneas
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $locations = [
            'Amazonas' => [
                'Puerto Ayacucho' => ['Atures' => ['Fernando Girón Tovar', 'Luis Alberto Gómez', 'Parhueña', 'Platanillal']],
                'San Fernando de Atabapo' => ['Atabapo' => ['Atabapo', 'Caname', 'Ucata', 'Yapacana']],
                'Maroa' => ['Maroa' => ['Maroa', 'Victorino']],
                'San Carlos de Río Negro' => ['Río Negro' => ['Casiquiare', 'Cocuy', 'San Carlos de Río Negro', 'Solano']],
                'San Juan de Manapiare' => ['Manapiare' => ['Manapiare', 'Alto Ventuari', 'Bajo Ventuari']],
                'Isla Ratón' => ['Autana' => ['Guayapo', 'Isla Ratón', 'Munduapo', 'Samariapo', 'Sipapo']],
                'La Esmeralda' => ['Alto Orinoco' => ['La Esmeralda', 'Huachamacare', 'Marawaka', 'Mavaca', 'Sierra Parima']],
            ],
            'Anzoátegui' => [
                'Barcelona' => ['Simón Bolívar' => ['El Carmen', 'San Cristóbal', 'Bergantín', 'Caigua', 'El Pilar', 'Naricual']],
                'Puerto La Cruz' => ['Sotillo' => ['Puerto La Cruz', 'Pozuelos']],
                'Lechería' => ['Diego Bautista Urbaneja' => ['Lechería', 'El Morro']],
                'Guanta' => ['Guanta' => ['Guanta', 'Chorrerón']],
                'Píritu' => ['Píritu' => ['Píritu', 'San Francisco']],
                'Puerto Píritu' => ['Peñalver' => ['Puerto Píritu', 'San Miguel', 'Sucre']],
                'Clarines' => ['Bruzual' => ['Clarines', 'Guanape', 'Sabana de Uchire']],
                'Onoto' => ['Cajigal' => ['Onoto', 'San Pablo']],
                'Valle de Guanape' => ['Carvajal' => ['Valle de Guanape', 'Santa Bárbara']],
                'Anaco' => ['Anaco' => ['Anaco', 'San Joaquín']],
                'Cantaura' => ['Freites' => ['Cantaura', 'Libertador', 'Santa Rosa', 'Urica']],
                'El Tigre' => ['Simón Rodríguez' => ['El Tigre', 'Las Mercedes']],
                'San José de Guanipa' => ['Guanipa' => ['San José de Guanipa']],
                'Pariaguán' => ['Miranda' => ['Pariaguán', 'Atapirire', 'Boca del Pao', 'El Pao']],
                'San Mateo' => ['Libertad' => ['San Mateo', 'El Carito']],
                'Aragua de Barcelona' => ['Aragua' => ['Aragua de Barcelona', 'Cachipo']],
                'Santa Ana' => ['Santa Ana' => ['Santa Ana', 'Pueblo Nuevo']],
                'El Chaparro' => ['McGregor' => ['El Chaparro', 'Tomás Alfaro Calatrava']],
                'Soledad' => ['Independencia' => ['Soledad', 'Mamo']],
                'Mapire' => ['Monagas' => ['Mapire', 'Piar', 'San Diego de Cabrutica', 'Santa Clara', 'Uverito', 'Zuata']],
            ],
            'Apure' => [
                'San Fernando de Apure' => ['San Fernando' => ['San Fernando', 'El Recreo', 'Peñalver', 'San Rafael de Atamaica']],
                'Achaguas' => ['Achaguas' => ['Achaguas', 'Apurito', 'El Yagual', 'Guachara', 'Mucuritas', 'Queseras del Medio']],
                'Biruaca' => ['Biruaca' => ['Biruaca']],
                'Bruzual' => ['Muñoz' => ['Bruzual', 'Mantecal', 'Quintero', 'Rincón Hondo', 'San Vicente']],
                'Elorza' => ['Rómulo Gallegos' => ['Elorza', 'La Trinidad', 'Puerto Miranda']],
                'Guasdualito' => ['Páez' => ['Guasdualito', 'Aramendi', 'El Amparo', 'San Camilo', 'Urdaneta']],
                'San Juan de Payara' => ['Pedro Camejo' => ['San Juan de Payara', 'Codazzi', 'Cunaviche']],
            ],
            'Aragua' => [
                'Maracay' => [
                    'Girardot' => ['Las Delicias', 'Madre María de San José', 'Joaquín Crespo', 'Pedro José Ovalles', 'José Casanova Godoy', 'Andrés Eloy Blanco', 'Los Tacariguas'],
                    'Mario Briceño Iragorry' => ['El Limón', 'Caña de Azúcar'],
                ],
                'Cagua' => ['Sucre' => ['Cagua', 'Bella Vista']],
                'La Victoria' => ['José Félix Ribas' => ['La Victoria', 'Castor Nieves Ríos', 'Las Guacamayas', 'Pao de Zárate', 'Zuata']],
                'Palo Negro' => ['Libertador' => ['Palo Negro', 'San Martín de Porres']],
                'Santa Rita' => ['Linares Alcántara' => ['Santa Rita', 'Francisco de Miranda', 'Monseñor Feliciano González']],
                'Turmero' => ['Santiago Mariño' => ['Turmero', 'Arevalo Aponte', 'Chuao', 'Samán de Güere', 'Alfredo Pacheco Miranda']],
                'Villa de Cura' => ['Zamora' => ['Villa de Cura', 'Magdaleno', 'San Francisco de Asís', 'Valles de Tucutunemo', 'Augusto Mijares']],
                'San Mateo' => ['Bolívar' => ['San Mateo']],
                'Las Tejerías' => ['Santos Michelena' => ['Las Tejerías']],
                'El Consejo' => ['José Rafael Revenga' => ['El Consejo']],
                'Colonia Tovar' => ['Tovar' => ['Colonia Tovar']],
                'San Casimiro' => ['San Casimiro' => ['San Casimiro', 'Güiripa', 'Ollas de Caramacate', 'Valle Morín']],
                'San Sebastián' => ['San Sebastián' => ['San Sebastián']],
                'Camatagua' => ['Camatagua' => ['Camatagua', 'Carmen de Cura']],
                'Barbacoas' => ['Urdaneta' => ['Barbacoas']],
                'Ocumare de la Costa' => ['Ocumare de la Costa de Oro' => ['Ocumare de la Costa']],
            ],
            'Barinas' => [
                'Barinas' => ['Barinas' => ['Barinas', 'Alfredo Arvelo Larriva', 'San Silvestre', 'Santa Inés', 'Santa Lucía', 'Torunos', 'El Carmen', 'Rómulo Betancourt', 'Corazón de Jesús', 'Ramón Ignacio Méndez', 'Alto Barinas', 'Manuel Palacio Fajardo', 'Juan Antonio Rodríguez Domínguez', 'Dominga Ortiz de Páez']],
                'Sabaneta' => ['Alberto Arvelo Torrealba' => ['Sabaneta', 'Rodríguez Domínguez']],
                'Barinitas' => ['Bolívar' => ['Barinitas', 'Altamira', 'Calderas']],
                'Barrancas' => ['Cruz Paredes' => ['Barrancas', 'El Socorro', 'Masparrito']],
                'Ciudad Bolivia' => ['Pedraza' => ['Ciudad Bolivia', 'José Félix Ribas', 'Páez', 'Ignacio Briceño']],
                'Obispos' => ['Obispos' => ['Obispos', 'El Real', 'La Luz', 'Los Guasimitos']],
                'Santa Bárbara' => ['Ezequiel Zamora' => ['Santa Bárbara', 'José Ignacio del Pumar', 'Pedro Briceño Méndez', 'Ramón Ignacio Méndez']],
                'Socopó' => ['Antonio José de Sucre' => ['Socopó', 'Andrés Bello', 'Nicolás Pulido']],
                'Libertad' => ['Rojas' => ['Libertad', 'Dolores', 'Palacios Fajardo', 'Simón Rodríguez']],
                'Arismendi' => ['Arismendi' => ['Arismendi', 'Guadarrama', 'La Unión', 'San Antonio']],
                'Ciudad de Nutrias' => ['Sosa' => ['Ciudad de Nutrias', 'El Regalo', 'Puerto de Nutrias', 'Santa Catalina']],
                'El Cantón' => ['Andrés Eloy Blanco' => ['El Cantón', 'Santa Cruz de Guacas', 'Puerto Vivas']],
            ],
            'Bolívar' => [
                'Ciudad Guayana' => ['Caroní' => ['Cachamay', 'Chirica', 'Dalla Costa', 'Once de Abril', 'Simón Bolívar', 'Unare', 'Universidad', 'Vista al Sol', 'Pozo Verde', 'Yocoima', '5 de julio']],
                'Ciudad Bolívar' => ['Angostura del Orinoco' => ['Catedral', 'Agua Salada', 'Marhuanta', 'La Sabanita', 'Vista Hermosa', 'José Antonio Páez', 'Orinoco', 'Panapana', 'Zea']],
                'Upata' => ['Piar' => ['Upata', 'Andrés Eloy Blanco', 'Pedro Cova']],
                'Caicara del Orinoco' => ['Cedeño' => ['Caicara del Orinoco', 'Altagracia', 'Ascensión Farreras', 'Guaniamo', 'La Urbana', 'Pijiguaos']],
                'El Callao' => ['El Callao' => ['El Callao']],
                'Guasipati' => ['Roscio' => ['Guasipati', 'Salom']],
                'Santa Elena de Uairén' => ['Gran Sabana' => ['Santa Elena de Uairén', 'Ikabarú']],
                'Tumeremo' => ['Sifontes' => ['Tumeremo', 'Dalla Costa', 'San Isidro']],
                'Maripa' => ['Sucre' => ['Maripa', 'Aripao', 'Guarataro', 'Las Majadas', 'Moitaco']],
                'Ciudad Piar' => ['Angostura' => ['Ciudad Piar', 'San Francisco', 'Santa Bárbara']],
                'El Palmar' => ['Padre Pedro Chien' => ['El Palmar']],
            ],
            'Carabobo' => [
                'Valencia' => ['Valencia' => ['Candelaria', 'Catedral', 'El Socorro', 'Miguel Peña', 'Rafael Urdaneta', 'San Blas', 'San José', 'Santa Rosa', 'Negro Primero']],
                'Naguanagua' => ['Naguanagua' => ['Naguanagua']],
                'San Diego' => ['San Diego' => ['San Diego']],
                'Guacara' => ['Guacara' => ['Guacara', 'Yagua', 'Ciudad Alianza']],
                'Puerto Cabello' => ['Puerto Cabello' => ['Bartolomé Salóm', 'Democracia', 'Fraternidad', 'Goaigoaza', 'Juan José Flores', 'Unión', 'Borburata', 'Patanemo']],
                'Bejuma' => ['Bejuma' => ['Bejuma', 'Canoabo', 'Simón Bolívar']],
                'Güigüe' => ['Carlos Arvelo' => ['Güigüe', 'Belén', 'Tacarigua']],
                'Mariara' => ['Diego Ibarra' => ['Mariara', 'Aguas Calientes']],
                'Morón' => ['Juan José Mora' => ['Morón', 'Urama']],
                'Tocuyito' => ['Libertador' => ['Tocuyito', 'Independencia']],
                'Montalbán' => ['Montalbán' => ['Montalbán']],
                'Miranda' => ['Miranda' => ['Miranda']],
                'San Joaquín' => ['San Joaquín' => ['San Joaquín']],
                'Los Guayos' => ['Los Guayos' => ['Los Guayos']],
            ],
            'Cojedes' => [
                'San Carlos' => ['San Carlos de Austria' => ['San Carlos', 'Juan Ángel Bravo', 'Manuel Manrique']],
                'Tinaquillo' => ['Tinaquillo' => ['Tinaquillo']],
                'El Baúl' => ['Girardot' => ['El Baúl', 'Sucre']],
                'Las Vegas' => ['Rómulo Gallegos' => ['Las Vegas']],
                'Libertad de Cojedes' => ['Ricaurte' => ['Libertad de Cojedes', 'El Amparo']],
                'Macapo' => ['Lima Blanco' => ['Macapo']],
                'El Pao' => ['Pao de San Juan Bautista' => ['El Pao']],
                'Tinaco' => ['Tinaco' => ['General en Jefe José Laurencio Silva']],
                'Cojedes' => ['Anzoátegui' => ['Cojedes', 'Juan de Mata Suárez']],
            ],
            'Delta Amacuro' => [
                'Tucupita' => ['Tucupita' => ['San José', 'José Vidal Marcano', 'Juan Millán', 'Leonardo Ruiz Pineda', 'Mariscal Antonio José de Sucre', 'Monseñor Argimiro García', 'San Rafael', 'Virgen del Valle']],
                'Casacoima' => ['Casacoima' => ['Sierra Imataca', 'Juan Bautista Arismendi', 'Manuel Piar', 'Rómulo Gallegos']],
                'Curiapo' => ['Antonio Díaz' => ['Curiapo', 'Almirante Luis Brión', 'Francisco Aniceto Lugo', 'Manuel Renaud', 'Padre Barral', 'Santos de Abelgas']],
                'Pedernales' => ['Pedernales' => ['Pedernales', 'Luis Beltrán Prieto Figueroa']],
            ],
            'Distrito Capital' => [
                'Caracas' => ['Libertador' => ['Antímano', 'Candelaria', 'Caricuao', 'Catedral', 'Coche', 'El Junquito', 'El Paraíso', 'El Recreo', 'El Valle', 'La Pastora', 'La Vega', 'Macarao', 'San Agustín', 'San Bernardino', 'San José', 'San Juan', 'San Pedro', 'Santa Rosalía', 'Santa Teresa', 'Sucre', '23 de enero']],
            ],
            'Falcón' => [
                'Coro' => ['Miranda' => ['San Antonio', 'San Gabriel', 'Santa Ana']],
                'Punto Fijo' => ['Carirubana' => ['Norte', 'Carirubana', 'Santa Ana', 'Urbana Punta Cardón']],
                'La Vela de Coro' => ['Colina' => ['La Vela de Coro', 'Acurigua', 'Guaibacoa', 'Las Calderas', 'Macoruca']],
                'Pueblo Nuevo' => ['Falcón' => ['Pueblo Nuevo', 'Adaure', 'Baraived', 'Buena Vista', 'Jadacaquiva', 'Moruy']],
                'Puerto Cumarebo' => ['Zamora' => ['Puerto Cumarebo', 'La Ciénaga', 'La Soledad', 'Pueblo Cumarebo', 'Zazárida']],
                'Tucacas' => ['Silva' => ['Tucacas', 'Boca de Aroa']],
                'Chichiriviche' => ['Monseñor Iturriza' => ['Chichiriviche']],
                'Dabajuro' => ['Dabajuro' => ['Dabajuro']],
                'Mene de Mauroa' => ['Mauroa' => ['Mene de Mauroa', 'San Félix', 'Casigua']],
                'Mirimire' => ['San Francisco' => ['Mirimire', 'Capital', 'San Francisco']],
                'Pedregal' => ['Democracia' => ['Pedregal', 'Agua Clara', 'Avaria', 'Piedra Grande', 'Purureche']],
                'San Juan de los Cayos' => ['Acosta' => ['San Juan de los Cayos', 'Capadare', 'La Pastora', 'Libertador']],
                'Santa Cruz de Bucaral' => ['Unión' => ['Santa Cruz de Bucaral', 'El Charal', 'Las Vegas del Tuy']],
                'Capatárida' => ['Buchivacoa' => ['Capatárida', 'Bariro', 'Borojó', 'Guajiro', 'Seque', 'Zazárida']],
                'San Luis' => ['Bolívar' => ['San Luis']],
                'Cabure' => ['Petit' => ['Cabure', 'Colina', 'Curimagua']],
                'Yaracal' => ['Cacique Manaure' => ['Yaracal']],
                'Píritu' => ['Píritu' => ['Píritu', 'San José de la Costa']],
                'Tocópero' => ['Tocópero' => ['Tocópero']],
                'Palmasola' => ['Palmasola' => ['Palmasola']],
                'La Cruz de Taratara' => ['Sucre' => ['La Cruz de Taratara']],
                'Santa Cruz de Los Taques' => ['Los Taques' => ['Santa Cruz de Los Taques', 'Judibana']],
            ],
            'Guárico' => [
                'San Juan de los Morros' => ['Juan Germán Roscio' => ['San Juan de los Morros', 'Cantagallo', 'Parapara']],
                'Calabozo' => ['Francisco de Miranda' => ['Calabozo', 'El Calvario', 'El Rastro', 'Guardatinajas']],
                'Valle de la Pascua' => ['Leonardo Infante' => ['Valle de la Pascua', 'Espino']],
                'Altagracia de Orituco' => ['José Tadeo Monagas' => ['Altagracia de Orituco', 'Lezama', 'Libertad de Orituco', 'Paso Real de Macaira', 'San Francisco de Macaira', 'San Rafael de Orituco', 'Soublette']],
                'Tucupido' => ['Ribas' => ['Tucupido', 'San Rafael de Laya']],
                'Zaraza' => ['Pedro Zaraza' => ['Zaraza', 'San José de Unare']],
                'El Sombrero' => ['Julián Mellado' => ['El Sombrero', 'Sosa']],
                'Las Mercedes' => ['Las Mercedes' => ['Las Mercedes', 'Cabruta', 'Santa Rita de Manapire']],
                'Camaguán' => ['Camaguán' => ['Camaguán', 'Puerto Miranda', 'Uverito']],
                'Chaguaramas' => ['Chaguaramas' => ['Chaguaramas']],
                'El Socorro' => ['El Socorro' => ['El Socorro']],
                'Guayabal' => ['San Gerónimo de Guayabal' => ['Guayabal', 'Cazorla']],
                'Ortiz' => ['Ortiz' => ['Ortiz', 'San Francisco de Tiznados', 'San José de Tiznados', 'San Lorenzo de Tiznados']],
                'Santa María de Ipire' => ['Santa María de Ipire' => ['Santa María de Ipire', 'Altamira']],
                'San José de Guaribe' => ['San José de Guaribe' => ['San José de Guaribe']],
            ],
            'La Guaira' => [
                'La Guaira' => ['Vargas' => ['Caraballeda', 'Carayaca', 'Caruao', 'Catia La Mar', 'El Junko', 'La Guaira', 'Macuto', 'Maiquetía', 'Naiguatá', 'Urimare', 'Raúl Leoni']],
            ],
            'Lara' => [
                'Barquisimeto' => [
                    'Iribarren' => ['Catedral', 'Concepción', 'El Cují', 'Juan de Villegas', 'Santa Rosa', 'Tamaca', 'Unión', 'Aguedo Felipe Alvarado', 'Buena Vista', 'Juárez'],
                    'Palavecino' => ['Cabudare', 'José Gregorio Bastidas', 'Agua Viva'],
                ],
                'Carora' => ['Torres' => ['Carora', 'Trinidad Samuel', 'Antonio Díaz', 'Camacaro', 'Castañeda', 'Cecilio Zubillaga', 'Chiquinquirá', 'El Blanco', 'Espinoza de los Monteros', 'Heriberto Arroyo', 'Lara', 'Las Mercedes', 'Manuel Morillo', 'Montes de Oca', 'Torres']],
                'El Tocuyo' => ['Morán' => ['El Tocuyo', 'Anzoátegui', 'Bolívar', 'Guarico', 'Hilario Luna y Luna', 'Humocaro Alto', 'Humocaro Bajo', 'La Candelaria']],
                'Quíbor' => ['Jiménez' => ['Quíbor', 'Diego de Lozada', 'José Bernardo Dorante', 'Coronel Mariano Peraza', 'Paraíso de San José', 'San Miguel', 'Tintorero', 'Cuara']],
                'Duaca' => ['Crespo' => ['Duaca', 'José María Blanco', 'Freitez']],
                'Sanare' => ['Andrés Eloy Blanco' => ['Sanare', 'Pío Tamayo', 'Quebrada Honda de Guache', 'Yacambú']],
                'Siquisique' => ['Urdaneta' => ['Siquisique', 'Moroturo', 'San Miguel', 'Xaguas']],
                'Sarare' => ['Simón Planas' => ['Sarare', 'Buría', 'Gustavo Vegas León']],
            ],
            'Mérida' => [
                'Mérida' => ['Libertador' => ['Antonio Spinetti Dini', 'Arias', 'Caracciolo Parra Pérez', 'Domingo Peña', 'El Llano', 'El Morro', 'Gonzalo Picón Febres', 'Jacinto Plaza', 'Juan Rodríguez Suárez', 'Lasso de la Vega', 'Los Nevados', 'Mariano Picón Salas', 'Milla', 'Osuna Rodríguez', 'Sagrario']],
                'El Vigía' => ['Alberto Adriani' => ['Presidente Betancourt', 'Presidente Páez', 'Presidente Rómulo Gallegos', 'Gabriel Picón González', 'Héctor Amable Mora', 'José Nucete Sardi', 'Pulido Méndez']],
                'Ejido' => ['Campo Elías' => ['Matriz', 'Montalbán', 'Acequias', 'Fernández Peña', 'Jají', 'La Mesa', 'San José']],
                'Tovar' => ['Tovar' => ['Tovar', 'El Amparo', 'El Llano', 'San Francisco']],
                'Bailadores' => ['Rivas Dávila' => ['Bailadores', 'Gerónimo Maldonado']],
                'La Grita' => ['Jáuregui' => ['Jáuregui', 'La Grita', 'Dr. Emilio Constantino Guerrero', 'Monseñor Miguel Antonio Salas']],
                'Timotes' => ['Miranda' => ['Timotes']],
                'Lagunillas' => ['Sucre' => ['Lagunillas', 'Chiguará', 'Estánques', 'La Trampa', 'Pueblo Nuevo del Sur']],
                'Mucuchíes' => ['Rangel' => ['Mucuchíes', 'Cacute', 'La Toma', 'Mucurubá', 'San Rafael']],
                'Tabay' => ['Santos Marquina' => ['Tabay']],
                'Santa Cruz de Mora' => ['Antonio Pinto Salinas' => ['Santa Cruz de Mora', 'Mesa de Las Palmas']],
                'Zea' => ['Zea' => ['Zea', 'Caño El Tigre']],
                'Arapuey' => ['Julio César Salas' => ['Arapuey']],
                'Nueva Bolivia' => ['Tulio Febres Cordero' => ['Nueva Bolivia', 'Independencia', 'María de la Concepción Palacios Blanco', 'Santa Apolonia']],
                'Tucaní' => ['Caracciolo Parra Olmedo' => ['Tucaní']],
                'Santa Elena de Arenales' => ['Obispo Ramos de Lora' => ['Santa Elena de Arenales', 'Eloy Paredes', 'San Rafael de Alcázar']],
                'La Azulita' => ['Andrés Bello' => ['La Azulita']],
                'Pueblo Llano' => ['Pueblo Llano' => ['Pueblo Llano']],
                'Santo Domingo' => ['Cardenal Quintero' => ['Santo Domingo']],
                'Torondoy' => ['Justo Briceño' => ['Torondoy']],
                'Aricagua' => ['Aricagua' => ['Aricagua', 'San Antonio']],
                'Canagua' => ['Arzobispo Chacón' => ['Canagua', 'Capurí', 'Chacantá', 'El Molino', 'Guaimaral', 'Mucuchachí', 'Mucutuy']],
                'Guaraque' => ['Guaraque' => ['Guaraque', 'Mesa de Quintero', 'Río Negro']],
                'Santa María de Caparo' => ['Padre Noguera' => ['Santa María de Caparo']],
            ],
            'Miranda' => [
                'Area Metropolitana de Caracas' => [
                    'Baruta' => ['El Cafetal', 'Las Minas de Baruta', 'Nuestra Señora del Rosario'],
                    'Chacao' => ['Chacao'],
                    'El Hatillo' => ['El Hatillo'],
                    'Sucre' => ['Caucagüita', 'Filas de Mariche', 'La Dolorita', 'Leoncio Martínez', 'Petare'],
                ],
                'Los Teques' => ['Guaicaipuro' => ['Los Teques', 'Altagracia de la Montaña', 'Cecilio Acosta', 'El Jarillo', 'Paracotos', 'San Pedro', 'Tácata']],
                'San Antonio de los Altos' => ['Los Salias' => ['San Antonio de los Altos']],
                'Carrizal' => ['Carrizal' => ['Carrizal']],
                'Ocumare del Tuy' => ['Lander' => ['Ocumare del Tuy', 'La Democracia', 'Santa Bárbara']],
                'Charallave' => ['Cristóbal Rojas' => ['Charallave', 'Las Brisas']],
                'Cúa' => ['Urdaneta' => ['Cúa', 'Nueva Cúa']],
                'Santa Teresa del Tuy' => ['Independencia' => ['Santa Teresa del Tuy', 'Cartanal']],
                'San Francisco de Yare' => ['Simón Bolívar' => ['San Francisco de Yare', 'San Antonio de Yare']],
                'Santa Lucía' => ['Paz Castillo' => ['Santa Lucía']],
                'Guarenas' => ['Plaza' => ['Guarenas']],
                'Guatire' => ['Zamora' => ['Guatire', 'Bolívar']],
                'Higuerote' => ['Brión' => ['Higuerote', 'Curiepe', 'Tacarigua']],
                'Río Chico' => ['Páez' => ['Río Chico', 'El Guapo', 'Inaepu', 'Paparo', 'Tacarigua de la Laguna']],
                'Caucagua' => ['Acevedo' => ['Caucagua', 'Aragüita', 'Arévalo González', 'Capaya', 'El Café', 'Marizapa', 'Panaquire', 'Ribas']],
                'San José de Barlovento' => ['Andrés Bello' => ['San José de Barlovento']],
                'Cúpira' => ['Pedro Gual' => ['Cúpira', 'Machurucuto']],
                'Mamporal' => ['Buroz' => ['Mamporal']],
            ],
            'Monagas' => [
                'Maturín' => ['Maturín' => ['Alto de los Godos', 'Boquerón', 'Las Cocuizas', 'San Simón', 'Santa Cruz', 'El Corozo', 'El Furrial', 'Jusepín', 'La Pica', 'San Vicente']],
                'Caripito' => ['Bolívar' => ['Caripito']],
                'Caripe' => ['Caripe' => ['Caripe', 'El Guácharo', 'La Guanota', 'Sabana de Piedra', 'San Agustín', 'Teresén']],
                'Caicara de Maturín' => ['Cedeño' => ['Caicara', 'Areo', 'San Félix', 'Viento Fresco']],
                'Punta de Mata' => ['Ezequiel Zamora' => ['Punta de Mata', 'El Tejero']],
                'Temblador' => ['Libertador' => ['Temblador', 'Las Alhuacas', 'Tabasca', 'Chaguaramas']],
                'Aragua de Maturín' => ['Piar' => ['Aragua de Maturín', 'Aparicio', 'Chaguaramal', 'El Pinto', 'Guanaguana', 'La Toscana', 'Taguaya']],
                'Quiriquire' => ['Punceres' => ['Quiriquire', 'Cachipo']],
                'Santa Bárbara' => ['Santa Bárbara' => ['Santa Bárbara', 'Morón']],
                'Barrancas del Orinoco' => ['Sotillo' => ['Barrancas del Orinoco', 'Los Barrancos de Fajardo']],
                'Uracoa' => ['Uracoa' => ['Uracoa']],
                'Aguasay' => ['Aguasay' => ['Aguasay']],
                'San Antonio de Capayacuar' => ['Acosta' => ['San Antonio de Capayacuar', 'Caripe del Guácharo']],
            ],
            'Nueva Esparta' => [
                'Porlamar' => ['Mariño' => ['Porlamar']],
                'Pampatar' => ['Maneiro' => ['Pampatar']],
                'La Asunción' => ['Arismendi' => ['La Asunción']],
                'Juan Griego' => ['Marcano' => ['Juan Griego', 'Adrián']],
                'El Valle del Espíritu Santo' => ['García' => ['El Valle del Espíritu Santo']],
                'Santa Ana' => ['Gómez' => ['Santa Ana', 'Bolívar', 'Guevara', 'Matasiete', 'Sucre']],
                'San Juan Bautista' => ['Díaz' => ['San Juan Bautista', 'Zabala']],
                'Punta de Piedras' => ['Tubores' => ['Punta de Piedras', 'Los Barales']],
                'Boca de Río' => ['Península de Macanao' => ['Boca de Río', 'San Francisco']],
                'La Plaza de Paraguachí' => ['Antolín del Campo' => ['La Plaza de Paraguachí']],
                'San Pedro de Coche' => ['Villalba' => ['San Pedro de Coche', 'Vicente Fuentes']],
            ],
            'Portuguesa' => [
                'Guanare' => ['Guanare' => ['Guanare', 'Córdoba', 'San José de la Montaña', 'San Juan de Guanaguanare', 'Virgen de la Coromoto']],
                'Acarigua' => ['Páez' => ['Acarigua', 'Payara', 'Pimpinela', 'Ramón Peraza']],
                'Araure' => ['Araure' => ['Araure', 'Río Acarigua']],
                'Villa Bruzual' => ['Turén' => ['Villa Bruzual', 'Canelones', 'Santa Cruz', 'San Isidro Labrador']],
                'Píritu' => ['Esteller' => ['Píritu', 'Uveral']],
                'Ospino' => ['Ospino' => ['Ospino', 'Aparición', 'La Estación']],
                'Biscucuy' => ['Sucre' => ['Biscucuy', 'Concepción', 'San Rafael de Palo Alzado', 'Uvencio Antonio Velásquez', 'San José de Saguaz', 'Villa Rosa']],
                'Guanarito' => ['Guanarito' => ['Guanarito', 'Trinidad de la Capilla', 'Divina Pastora']],
                'Boconoíto' => ['San Genaro de Boconoíto' => ['Boconoíto', 'Antolín Tovar Anquino']],
                'Papelón' => ['Papelón' => ['Papelón', 'Caño Delgadito']],
                'El Playón' => ['Santa Rosalía' => ['El Playón', 'Florida', 'Trinidad de la Capilla']],
                'Agua Blanca' => ['Agua Blanca' => ['Agua Blanca']],
            ],
            'Sucre' => [
                'Cumaná' => ['Sucre' => ['Altagracia', 'Ayacucho', 'San Juan', 'Santa Inés', 'Valentín Valiente', 'Raúl Leoni', 'Gran Mariscal']],
                'Carúpano' => ['Bermúdez' => ['Carúpano', 'Santa Catalina', 'Santa Rosa', 'Santa Teresa', 'Bolívar', 'Macarapana']],
                'Güiria' => ['Valdez' => ['Güiria', 'Bideau', 'Cristóbal Colón', 'Punta de Piedras']],
                'Cariaco' => ['Ribero' => ['Cariaco', 'Catuaro', 'Rendón', 'Santa Cruz', 'Santa María']],
                'Cumanacoa' => ['Montes' => ['Cumanacoa', 'Arenas', 'Aricagua', 'Cocollar', 'San Fernando', 'San Lorenzo']],
                'Río Caribe' => ['Arismendi' => ['Río Caribe', 'Antonio José de Sucre', 'El Morro de Puerto Santo', 'Puerto Santo', 'San Juan de las Galdonas']],
                'El Pilar' => ['Benítez' => ['El Pilar', 'El Rincón', 'General Francisco Antonio Vásquez', 'Guaraúnos', 'Tunapuicito', 'Unión']],
                'Irapa' => ['Mariño' => ['Irapa', 'Campo Claro', 'Marabal', 'San Antonio de Irapa', 'Soro']],
                'Araya' => ['Cruz Salmerón Acosta' => ['Araya', 'Chacopata', 'Manicuare']],
                'Casanay' => ['Andrés Eloy Blanco' => ['Casanay']],
                'San Antonio del Golfo' => ['Mejía' => ['San Antonio del Golfo']],
                'Tunapuy' => ['Libertador' => ['Tunapuy', 'Campo Elías']],
                'Yaguaraparo' => ['Cajigal' => ['Yaguaraparo', 'Libertad', 'El Paujil']],
                'Marigüitar' => ['Bolívar' => ['Marigüitar']],
                'San José de Aerocuar' => ['Andrés Mata' => ['San José de Aerocuar', 'Río Casanay', 'Tavera Acosta']],
            ],
            'Táchira' => [
                'San Cristóbal' => ['San Cristóbal' => ['La Concordia', 'Pedro María Morantes', 'San Juan Bautista', 'San Sebastián', 'Dr. Francisco Romero Lobo']],
                'Táriba' => ['Cárdenas' => ['Táriba', 'Amenodoro Rangel Lamus', 'La Florida']],
                'La Fría' => ['García de Hevia' => ['La Fría', 'Boca de Grita', 'José Antonio Páez']],
                'La Grita' => ['Jáuregui' => ['La Grita', 'Dr. Emilio Constantino Guerrero', 'Monseñor Miguel Antonio Salas']],
                'Colón' => ['Ayacucho' => ['Colón', 'Rivas Berti', 'San Pedro del Río']],
                'Rubio' => ['Junín' => ['Rubio', 'Bramón', 'La Petrólea', 'Quinimarí']],
                'San Antonio del Táchira' => ['Bolívar' => ['San Antonio del Táchira', 'Dr. Palotal', 'General Juan Vicente Gómez', 'Isaías Medina Angarita']],
                'Ureña' => ['Pedro María Ureña' => ['Ureña', 'Nueva Arcadia']],
                'Capacho Nuevo' => ['Independencia' => ['Capacho Nuevo', 'Juan Germán Roscio', 'Román Cárdenas']],
                'Capacho Viejo' => ['Libertad' => ['Capacho Viejo']],
                'Michelena' => ['Michelena' => ['Michelena']],
                'Palmira' => ['Guásimos' => ['Palmira']],
                'Queniquea' => ['Sucre' => ['Queniquea', 'Eleazar López Contreras', 'San Pablo']],
                'San Rafael del Piñal' => ['Fernández Feo' => ['San Rafael del Piñal', 'Alberto Adriani', 'Santo Domingo']],
                'Santa Ana del Táchira' => ['Córdoba' => ['Santa Ana del Táchira']],
                'Coloncito' => ['Panamericano' => ['Coloncito', 'La Palmita']],
                'Abejales' => ['Libertador' => ['Abejales', 'Doradas', 'Emeterio Ochoa', 'San Joaquín de Navay']],
                'Pregonero' => ['Uribante' => ['Pregonero', 'Cárdenas', 'Juan Pablo Peñaloza', 'Potosí']],
                'Cordero' => ['Andrés Bello' => ['Cordero']],
                'El Cobre' => ['José María Vargas' => ['El Cobre']],
                'Seboruco' => ['Seboruco' => ['Seboruco']],
                'Delicias' => ['Rafael Urdaneta' => ['Delicias', 'Páez']],
                'San Josecito' => ['Torbes' => ['San Josecito', 'Konarek']],
                'Umuquena' => ['San Judas Tadeo' => ['Umuquena']],
            ],
            'Trujillo' => [
                'Trujillo' => ['Trujillo' => ['Chiquinquirá', 'Cristóbal Mendoza', 'Cruz Carrillo', 'Matriz', 'Monseñor Carrillo', 'Tres Esquinas', 'Andrés Linares']],
                'Valera' => ['Valera' => ['Juan Ignacio Montilla', 'La Beatriz', 'La Puerta', 'Mendoza del Valle de Momboy', 'Mercedes Díaz', 'San Luis']],
                'Boconó' => ['Boconó' => ['Boconó', 'El Carmen', 'Mosquey', 'Ayacucho', 'Burbusay', 'General Rivas', 'Guaramacal', 'La Vega de Guaramacal', 'Monseñor Jáuregui', 'Rafael Rangel', 'San José', 'San Miguel']],
                'Pampán' => ['Pampán' => ['Pampán', 'Flor de Patria', 'La Paz', 'Santa Ana']],
                'Pampanito' => ['Pampanito' => ['Pampanito', 'La Concepción', 'Pampanito II']],
                'Carache' => ['Carache' => ['Carache', 'La Concepción', 'Cuicas', 'Panamericana', 'Santa Cruz']],
                'Escuque' => ['Escuque' => ['Escuque', 'La Unión', 'Sabana Libre', 'Santa Rita']],
                'Betijoque' => ['Rafael Rangel' => ['Betijoque', 'José Gregorio Hernández', 'La Pueblita', 'Los Cedros']],
                'Sabana de Mendoza' => ['Sucre' => ['Sabana de Mendoza', 'El Paraíso', 'Junín', 'Valmore Rodríguez']],
                'Monay' => ['Candelaria' => ['Chejendé', 'Arnoldo Gabaldón', 'Bolivia', 'Carrillo', 'Cegarra', 'La Paz', 'Santa Ana']],
                'Carvajal' => ['San Rafael de Carvajal' => ['Carvajal', 'Antonio Nicolás Briceño', 'José Leonardo Suárez', 'Campo Alegre']],
                'La Quebrada' => ['Urdaneta' => ['La Quebrada', 'Cabimbú', 'Jajó', 'La Mesa de Esnujaque', 'Santiago', 'Tuñame']],
                'El Dividive' => ['Miranda' => ['El Dividive', 'Agua Santa', 'Agua Caliente', 'El Cenizo']],
                'Santa Isabel' => ['Andrés Bello' => ['Santa Isabel', 'Araguaney', 'El Jaguito', 'La Esperanza']],
                'Monte Carmelo' => ['Monte Carmelo' => ['Monte Carmelo', 'Buena Vista', 'Santa María del Horcón']],
                'El Paradero' => ['José Felipe Márquez Cañizales' => ['El Paradero', 'Antonio José de Sucre', 'José Felipe Márquez Cañizales']],
                'La Ceiba' => ['La Ceiba' => ['Santa Apolonia', 'El Progreso', 'La Ceiba', 'Tres de Febrero']],
                'Sabana Grande' => ['Bolívar' => ['Sabana Grande', 'Cheregüé', 'Granados']],
            ],
            'Yaracuy' => [
                'San Felipe' => [
                    'San Felipe' => ['San Felipe', 'Albarico', 'Marín'],
                    'Independencia' => ['Independencia'],
                    'Cocorote' => ['Cocorote'],
                ],
                'Yaritagua' => ['Peña' => ['Yaritagua', 'San Andrés']],
                'Chivacoa' => ['Bruzual' => ['Chivacoa', 'Campo Elías']],
                'Nirgua' => ['Nirgua' => ['Nirgua', 'Salom', 'Temerla']],
                'Aroa' => ['Bolívar' => ['Aroa']],
                'Guama' => ['Sucre' => ['Guama']],
                'Urachiche' => ['Urachiche' => ['Urachiche']],
                'Sabana de Parra' => ['Páez' => ['Sabana de Parra', 'José Antonio Páez']],
                'Yumare' => ['Manuel Monge' => ['Yumare']],
                'San Pablo' => ['Arístides Bastidas' => ['San Pablo']],
                'Boraure' => ['La Trinidad' => ['Boraure']],
                'Farriar' => ['Veroes' => ['Farriar', 'El Guayabo']],
            ],
            'Zulia' => [
                'Maracaibo' => ['Maracaibo' => ['Antonio Borjas Romero', 'Bolívar', 'Cacique Mara', 'Caracciolo Parra Pérez', 'Cecilio Acosta', 'Cristo de Aranza', 'Coquivacoa', 'Chiquinquirá', 'Francisco Eugenio Bustamante', 'Idelfonso Vásquez', 'Juana de Ávila', 'Luis Hurtado Higuera', 'Manuel Dagnino', 'Olegario Villalobos', 'Raúl Leoni', 'Santa Lucía', 'Venancio Pulgar', 'San Isidro']],
                'San Francisco' => ['San Francisco' => ['San Francisco', 'El Bajo', 'Domitila Flores', 'Francisco Ochoa', 'Los Cortijos', 'Marcial Hernández']],
                'Cabimas' => ['Cabimas' => ['Ambrosio', 'Carmen Herrera', 'La Rosa', 'Germán Ríos Linares', 'Jorge Hernández', 'Rómulo Betancourt', 'San Benito', 'Arístides Calvani', 'Punta Gorda']],
                'Ciudad Ojeda' => ['Lagunillas' => ['Ciudad Ojeda', 'El Danto', 'Libertad', 'Alonso de Ojeda', 'Campo Lara', 'Eleazar López Contreras']],
                'La Villa del Rosario' => ['Rosario de Perijá' => ['La Villa del Rosario', 'Donaldo García', 'El Rosario', 'Sixto Zambrano']],
                'Machiques' => ['Machiques de Perijá' => ['Libertad', 'Bartolomé de las Casas', 'Río Negro', 'San José de Perijá']],
                'San Carlos del Zulia' => ['Colón' => ['San Carlos del Zulia', 'Moralito', 'San Bárbara', 'Santa Cruz del Zulia', 'Urribarrí']],
                'Encontrados' => ['Catatumbo' => ['Encontrados', 'Udón Pérez']],
                'Casigua El Cubo' => ['Jesús María Semprún' => ['Casigua El Cubo', 'Barí']],
                'La Concepción' => ['Jesús Enrique Lossada' => ['La Concepción', 'José Ramón Yépez', 'Mariano Parra León', 'San José']],
                'San Rafael de El Moján' => ['Mara' => ['San Rafael de El Moján', 'La Sierrita', 'Las Parcelas', 'Luis de Vicente', 'Ricaurte', 'Tamare']],
                'Sinamaica' => ['Guajira' => ['Sinamaica', 'Alta Guajira', 'Elías Sánchez Rubio', 'Guajira']],
                'Altagracia' => ['Miranda' => ['Altagracia', 'Ana María Campos', 'Faría', 'San Antonio', 'San José']],
                'Santa Rita' => ['Santa Rita' => ['Santa Rita', 'El Mene', 'Pedro Lucas Urribarrí', 'José Cenobio Urribarrí']],
                'Bachaquero' => ['Valmore Rodríguez' => ['Bachaquero', 'La Victoria', 'Rafael Urdaneta']],
                'Mene Grande' => ['Baralt' => ['San Timoteo', 'General Urdaneta', 'Libertador', 'Manuel Guanipa Matos', 'Marcelino Briceño', 'Pueblo Nuevo']],
                'Bobures' => ['Sucre' => ['Bobures', 'Gibraltar', 'Heras', 'Monseñor Arturo Celestino Álvarez', 'Rómulo Gallegos', 'El Batey']],
                'Pueblo Nuevo-El Chivo' => ['Francisco Javier Pulgar' => ['Pueblo Nuevo-El Chivo', 'Agustín Codazzi', 'Carlos Quevedo', 'Francisco Javier Pulgar']],
                'Tía Juana' => ['Simón Bolívar' => ['Tía Juana', 'Manuel Manrique', 'Rafael María Baralt']],
                'Isla de Toas' => ['Almirante Padilla' => ['Isla de Toas', 'Monagas']],
            ],
        ];

        foreach ($locations as $stateName => $cities) {
            $state = State::create(['name' => $stateName]);
            foreach ($cities as $cityName => $municipalities) {
                $city = $state->cities()->create(['name' => $cityName]);
                foreach ($municipalities as $municipalityName => $parishes) {
                    $municipality = $city->municipalities()->create(['name' => $municipalityName]);
                    foreach ($parishes as $parishName) {
                        $municipality->parishes()->create(['name' => $parishName]);
                    }
                }
            }
        }
    }
}
